"""
Preset scenarios and sample subgraphs for LegalGraphRAG UI.
"""

from typing import Dict, List, Any

PRESET_SCENARIOS: List[Dict[str, Any]] = [
    {
        "id": "loan_default",
        "title": "Tranh chấp Hợp đồng Vay & Lãi suất quá hạn",
        "badge": "Vay tài sản",
        "icon": "banknote",
        "scenario_key": "loan",
        "fact": "Ngày 15/03/2022, ông Nguyễn Văn A cho ông Trần Văn B vay 200.000.000 đồng để kinh doanh, có lập giấy biên nhận viết tay có chữ ký hai bên. Thời hạn vay là 12 tháng (đến 15/03/2023), thỏa thuận miệng lãi suất 2.5%/tháng (30%/năm). Đến hạn, ông B chỉ trả được 50.000.000 đồng tiền gốc và xin khất nợ nhiều lần. Đến tháng 06/2024, ông A yêu cầu ông B hoàn trả nợ gốc còn lại 150.000.000 đồng cùng toàn bộ tiền lãi theo thỏa thuận nhưng ông B chối bỏ, cho rằng lãi suất quá cao là vi phạm pháp luật nên không chịu trả bất kỳ khoản nào.",
        "tags": [
            "Điều 463 BLDS 2015",
            "Điều 466 BLDS 2015",
            "Điều 468 BLDS 2015 (Trần lãi suất 20%)",
            "NQ 01/2019/NQ-HĐTP",
        ],
    },
    {
        "id": "deposit_dispute",
        "title": "Tranh chấp Đặt cọc Mua bán Nhà đất (Phạt cọc)",
        "badge": "Đặt cọc & Nhà đất",
        "icon": "home",
        "scenario_key": "deposit",
        "fact": "Bà Lê Thị M ký hợp đồng đặt cọc 300.000.000 đồng với ông Hoàng Văn N để mua một thửa đất ở với giá trị 3.500.000.000 đồng. Hợp đồng đặt cọc quy định trong vòng 30 ngày kể từ 10/01/2024, hai bên phải ra văn phòng công chứng ký hợp đồng chuyển nhượng chính thức. Nếu bên bán từ chối bán thì phải đền bù gấp đôi số tiền cọc (600.000.000 đồng). Đến ngày hẹn, ông N thông báo có người khác trả giá cao hơn nên hủy giao dịch và chỉ đồng ý trả lại 300.000.000 đồng tiền cọc gốc mà không chịu phạt cọc.",
        "tags": ["Điều 328 BLDS 2015 (Đặt cọc)", "Điều 117 BLDS 2015", "Án lệ 25/2018/AL"],
    },
    {
        "id": "inheritance_dispute",
        "title": "Tranh chấp Di sản Thừa kế & Di chúc miệng",
        "badge": "Thừa kế & QSDĐ",
        "icon": "scroll",
        "scenario_key": "inheritance",
        "fact": "Ông Phan Văn H mất năm 2023, để lại di sản là ngôi nhà gắn liền với quyền sử dụng đất 200m2 mang tên ông. Ông H có 3 người con C, D và E (vợ ông H đã mất). Trước khi mất trong bệnh viện, ông H nói miệng để lại nhà cho con út E nhưng không lập văn bản và không có người làm chứng độc lập. Sau khi ông mất, E quản lý toàn bộ nhà đất và không chia cho các anh chị C, D. Anh C và chị D khởi kiện yêu cầu chia thừa kế theo pháp luật.",
        "tags": [
            "Điều 624 BLDS 2015",
            "Điều 629 BLDS 2015 (Di chúc miệng)",
            "Điều 630 BLDS 2015",
            "Điều 651 BLDS 2015 (Hàng thừa kế)",
        ],
    },
    {
        "id": "tort_damage",
        "title": "Bồi thường Thiệt hại Ngoài Hợp đồng (Cây đổ đè hỏng ô tô)",
        "badge": "Bồi thường thiệt hại",
        "icon": "car",
        "scenario_key": "tort",
        "fact": "Trong một cơn giông lốc vào chiều ngày 20/05/2024, cây xà cừ cổ thụ trong khuôn viên của Công ty X bị bật gốc gãy đổ đè bẹp xe ô tô của anh Vũ Văn K đang đậu hợp pháp tại bãi đỗ xe lề đường. Thiệt hại sửa chữa xe là 180.000.000 đồng. Anh K yêu cầu Công ty X bồi thường. Công ty X từ chối với lý do cây đổ do thiên tai bão lốc (sự kiện bất khả kháng) nên công ty không có lỗi.",
        "tags": [
            "Điều 584 BLDS 2015",
            "Điều 585 BLDS 2015",
            "Điều 604 BLDS 2015 (Cây cối gây thiệt hại)",
        ],
    },
]

SAMPLE_GRAPHS: Dict[str, Dict[str, Any]] = {
    "overview": {
        "query": "Toàn cảnh Mạng lưới Đồ thị Tri thức Pháp luật Dân sự Việt Nam (Legal Knowledge Graph)",
        "nodes": [
            # Clusters
            {
                "id": "cluster_hop_dong",
                "label": "Cụm: Hợp đồng & Nghĩa vụ Dân sự",
                "type": "Cluster",
                "color": "#8b5cf6",
                "value": 28,
                "title": "Bao gồm các quy định chung về giao kết, thực hiện, bồi thường thiệt hại hợp đồng",
            },
            {
                "id": "cluster_thua_ke",
                "label": "Cụm: Thừa kế & Quyền Sở Hữu",
                "type": "Cluster",
                "color": "#8b5cf6",
                "value": 26,
                "title": "Bao gồm thừa kế theo di chúc, thừa kế theo pháp luật, xác lập quyền tài sản",
            },
            {
                "id": "cluster_boi_thuong",
                "label": "Cụm: Bồi thường Ngoài Hợp đồng",
                "type": "Cluster",
                "color": "#8b5cf6",
                "value": 25,
                "title": "Bao gồm trách nhiệm bồi thường do tài sản, nguồn nguy hiểm cao độ, súc vật, cây cối",
            },
            # Laws
            {
                "id": "law_d463",
                "label": "Điều 463: HĐ Vay tài sản",
                "type": "Law",
                "color": "#10b981",
                "value": 18,
                "title": "Hợp đồng vay tài sản là sự thỏa thuận giữa các bên, bên vay có nghĩa vụ trả lại tài sản cùng loại.",
            },
            {
                "id": "law_d466",
                "label": "Điều 466: Nghĩa vụ trả nợ",
                "type": "Law",
                "color": "#10b981",
                "value": 18,
                "title": "Bên vay tài sản là tiền thì phải trả đủ tiền khi đến hạn; nếu tài sản là vật thì phải trả vật cùng loại.",
            },
            {
                "id": "law_d468",
                "label": "Điều 468: Lãi suất vay",
                "type": "Law",
                "color": "#10b981",
                "value": 20,
                "title": "Lãi suất vay do các bên thỏa thuận nhưng không được vượt quá 20%/năm của khoản tiền vay.",
            },
            {
                "id": "law_d328",
                "label": "Điều 328: Đặt cọc",
                "type": "Law",
                "color": "#10b981",
                "value": 20,
                "title": "Đặt cọc là việc một bên giao cho bên kia một khoản tiền/vật có giá trị để bảo đảm giao kết hoặc thực hiện hợp đồng.",
            },
            {
                "id": "law_d624",
                "label": "Điều 624: Di chúc",
                "type": "Law",
                "color": "#10b981",
                "value": 17,
                "title": "Di chúc là sự thể hiện ý chí của cá nhân nhằm chuyển tài sản của mình cho người khác sau khi chết.",
            },
            {
                "id": "law_d629",
                "label": "Điều 629: Di chúc miệng",
                "type": "Law",
                "color": "#10b981",
                "value": 17,
                "title": "Trường hợp tính mạng bị cái chết đe dọa và không thể lập di chúc bằng văn bản thì có thể lập di chúc miệng.",
            },
            {
                "id": "law_d651",
                "label": "Điều 651: Thừa kế theo pháp luật",
                "type": "Law",
                "color": "#10b981",
                "value": 19,
                "title": "Hàng thừa kế thứ nhất gồm: vợ, chồng, cha đẻ, mẹ đẻ, cha nuôi, mẹ nuôi, con đẻ, con nuôi của người chết.",
            },
            {
                "id": "law_d584",
                "label": "Điều 584: Căn cứ bồi thường",
                "type": "Law",
                "color": "#10b981",
                "value": 18,
                "title": "Người nào có hành vi xâm phạm tính mạng, sức khỏe, danh dự, tài sản của người khác mà gây thiệt hại thì phải bồi thường.",
            },
            {
                "id": "law_d604",
                "label": "Điều 604: Cây cối gây thiệt hại",
                "type": "Law",
                "color": "#10b981",
                "value": 18,
                "title": "Chủ sở hữu, người chiếm hữu, người được giao quản lý cây cối phải bồi thường thiệt hại do cây cối gây ra.",
            },
            # Cases / Precedents
            {
                "id": "case_vay_01",
                "label": "Bản án 42/2023/DS-ST (Tranh chấp vay nợ)",
                "type": "Case",
                "color": "#3b82f6",
                "value": 15,
                "title": "Tòa án buộc bên vay hoàn trả nợ gốc và điều chỉnh mức lãi suất vượt trần 20%/năm về đúng mức quy định.",
            },
            {
                "id": "case_coc_02",
                "label": "Bản án 18/2023/DS-PT (Phạt cọc nhà đất)",
                "type": "Case",
                "color": "#3b82f6",
                "value": 15,
                "title": "Tuyên bên bán vi phạm nghĩa vụ giao kết hợp đồng chuyển nhượng QSDĐ, phạt cọc gấp đôi số tiền đã nhận.",
            },
            {
                "id": "case_al_25",
                "label": "Án lệ số 25/2018/AL (Về đặt cọc)",
                "type": "Case",
                "color": "#f59e0b",
                "value": 18,
                "title": "Án lệ xác định trách nhiệm phạt cọc khi có sự kiện khách quan tác động đến khả năng thực hiện giao dịch.",
            },
            {
                "id": "case_thua_ke_03",
                "label": "Bản án 105/2022/DS-ST (Chia thừa kế đất đai)",
                "type": "Case",
                "color": "#3b82f6",
                "value": 15,
                "title": "Bác bỏ hiệu lực di chúc miệng không người làm chứng, chia đều di sản cho 3 người con thuộc hàng thừa kế 1.",
            },
            {
                "id": "case_cay_do_04",
                "label": "Bản án 29/2024/DS-ST (Bồi thường cây đổ đè xe)",
                "type": "Case",
                "color": "#3b82f6",
                "value": 15,
                "title": "Buộc cơ quan quản lý cây xanh bồi thường toàn bộ chi phí sửa chữa xe ô tô do thiếu trách nhiệm cắt tỉa trước mùa mưa.",
            },
        ],
        "edges": [
            {
                "from": "law_d463",
                "to": "cluster_hop_dong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d466",
                "to": "cluster_hop_dong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d468",
                "to": "cluster_hop_dong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d328",
                "to": "cluster_hop_dong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "case_vay_01",
                "to": "law_d463",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_vay_01",
                "to": "law_d466",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_vay_01",
                "to": "law_d468",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_coc_02",
                "to": "law_d328",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_coc_02",
                "to": "case_al_25",
                "label": "CITES_PRECEDENT",
                "color": "#f59e0b",
            },
            {"from": "case_al_25", "to": "law_d328", "label": "INTERPRETS_LAW", "color": "#10b981"},
            {
                "from": "law_d624",
                "to": "cluster_thua_ke",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d629",
                "to": "cluster_thua_ke",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d651",
                "to": "cluster_thua_ke",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "case_thua_ke_03",
                "to": "law_d629",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_thua_ke_03",
                "to": "law_d651",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "law_d584",
                "to": "cluster_boi_thuong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d604",
                "to": "cluster_boi_thuong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "case_cay_do_04",
                "to": "law_d584",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_cay_do_04",
                "to": "law_d604",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
        ],
    },
    "loan": {
        "query": "Vụ án Tranh chấp Hợp đồng Vay 200tr & Lãi suất vượt trần 20%",
        "nodes": [
            {
                "id": "query_loan",
                "label": "Vụ việc đang xét: Vay 200tr không trả",
                "type": "Query",
                "color": "#ef4444",
                "value": 26,
                "title": "Bên vay chối nợ gốc 150tr và phản đối mức lãi suất 2.5%/tháng.",
            },
            {
                "id": "cluster_hop_dong",
                "label": "Cụm: Hợp đồng Vay tài sản",
                "type": "Cluster",
                "color": "#8b5cf6",
                "value": 24,
                "title": "Quy định Hợp đồng Vay tài sản và Lãi suất",
            },
            {
                "id": "law_d463",
                "label": "Điều 463: HĐ Vay tài sản",
                "type": "Law",
                "color": "#10b981",
                "value": 18,
                "title": "Hợp đồng vay tài sản là sự thỏa thuận giữa các bên.",
            },
            {
                "id": "law_d466",
                "label": "Điều 466: Nghĩa vụ trả nợ của bên vay",
                "type": "Law",
                "color": "#10b981",
                "value": 20,
                "title": "Bên vay phải hoàn trả nợ gốc khi đến hạn dù có tranh chấp về lãi.",
            },
            {
                "id": "law_d468",
                "label": "Điều 468: Lãi suất theo thỏa thuận",
                "type": "Law",
                "color": "#10b981",
                "value": 22,
                "title": "Mức trần lãi suất 20%/năm. Phần vượt quá 20% bị vô hiệu.",
            },
            {
                "id": "law_nq01",
                "label": "NQ 01/2019/NQ-HĐTP: Hướng dẫn Lãi suất",
                "type": "Law",
                "color": "#10b981",
                "value": 18,
                "title": "Quy định cách tính lãi trên nợ gốc quá hạn và xử lý phần lãi vượt trần.",
            },
            {
                "id": "case_vay_01",
                "label": "Bản án 42/2023/DS-ST (HĐ vay giấy tay)",
                "type": "Case",
                "color": "#3b82f6",
                "value": 16,
                "title": "Giấy tay vẫn có hiệu lực pháp lý xác nhận nợ gốc; Tòa giảm lãi về 20%/năm.",
            },
            {
                "id": "case_vay_02",
                "label": "Bản án 91/2022/DS-PT (Chối bỏ nghĩa vụ trả nợ)",
                "type": "Case",
                "color": "#3b82f6",
                "value": 16,
                "title": "Không trả nợ bị tính lãi chậm trả 10%/năm theo Điều 468 khoản 2.",
            },
        ],
        "edges": [
            {
                "from": "query_loan",
                "to": "law_d466",
                "label": "ÁP DỤNG TRỰC TIẾP",
                "color": "#ef4444",
            },
            {
                "from": "query_loan",
                "to": "law_d468",
                "label": "ĐIỀU CHỈNH LÃI SUẤT",
                "color": "#ef4444",
            },
            {
                "from": "query_loan",
                "to": "case_vay_01",
                "label": "TIỀN LỆ TƯƠNG ĐỒNG (92%)",
                "color": "#3b82f6",
            },
            {
                "from": "law_d463",
                "to": "cluster_hop_dong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d466",
                "to": "cluster_hop_dong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d468",
                "to": "cluster_hop_dong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_nq01",
                "to": "law_d468",
                "label": "HƯỚNG DẪN ÁP DỤNG",
                "color": "#10b981",
            },
            {
                "from": "case_vay_01",
                "to": "law_d466",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_vay_01",
                "to": "law_d468",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_vay_02",
                "to": "law_d466",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
        ],
    },
    "deposit": {
        "query": "Vụ án Tranh chấp Đặt cọc Mua bán Nhà đất 300 triệu",
        "nodes": [
            {
                "id": "query_deposit",
                "label": "Vụ việc đang xét: Đặt cọc 300tr bị hủy cọc",
                "type": "Query",
                "color": "#ef4444",
                "value": 26,
                "title": "Bên bán hủy cọc bán cho người khác trả giá cao hơn, đòi phạt cọc gấp đôi.",
            },
            {
                "id": "cluster_hop_dong",
                "label": "Cụm: Biện pháp bảo đảm nghĩa vụ",
                "type": "Cluster",
                "color": "#8b5cf6",
                "value": 24,
                "title": "Quy định Đặt cọc, Ký quỹ, Thế chấp",
            },
            {
                "id": "law_d328",
                "label": "Điều 328: Đặt cọc & Phạt cọc",
                "type": "Law",
                "color": "#10b981",
                "value": 22,
                "title": "Bên nhận cọc từ chối giao kết phải trả tiền cọc và một khoản tương đương giá trị tài sản đặt cọc.",
            },
            {
                "id": "law_d117",
                "label": "Điều 117: Điều kiện hiệu lực giao dịch",
                "type": "Law",
                "color": "#10b981",
                "value": 18,
                "title": "Chủ thể có năng lực hành vi dân sự, tự nguyện, không vi phạm điều cấm của luật.",
            },
            {
                "id": "case_al_25",
                "label": "Án lệ số 25/2018/AL (Về phạt cọc)",
                "type": "Case",
                "color": "#f59e0b",
                "value": 20,
                "title": "Án lệ xác định bên đơn phương hủy cọc phải bồi thường phạt cọc gấp đôi nếu không có lý do bất khả kháng.",
            },
            {
                "id": "case_coc_02",
                "label": "Bản án 18/2023/DS-PT (Đà Nẵng)",
                "type": "Case",
                "color": "#3b82f6",
                "value": 16,
                "title": "Tuyên chấp nhận toàn bộ yêu cầu của người mua, buộc bên bán bồi thường 600 triệu đồng.",
            },
        ],
        "edges": [
            {
                "from": "query_deposit",
                "to": "law_d328",
                "label": "ÁP DỤNG ĐIỀU 328 (PHẠT CỌC)",
                "color": "#ef4444",
            },
            {
                "from": "query_deposit",
                "to": "case_al_25",
                "label": "ÁP DỤNG ÁN LỆ 25 (95%)",
                "color": "#f59e0b",
            },
            {
                "from": "law_d328",
                "to": "cluster_hop_dong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "case_coc_02",
                "to": "law_d328",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_coc_02",
                "to": "case_al_25",
                "label": "CITES_PRECEDENT",
                "color": "#f59e0b",
            },
        ],
    },
    "inheritance": {
        "query": "Tranh chấp Di sản Thừa kế Nhà đất & Hiệu lực Di chúc miệng",
        "nodes": [
            {
                "id": "query_inherit",
                "label": "Vụ việc đang xét: Tranh chấp di chúc miệng",
                "type": "Query",
                "color": "#ef4444",
                "value": 26,
                "title": "Di chúc miệng tại bệnh viện không người làm chứng, các con kiện chia đều di sản.",
            },
            {
                "id": "cluster_thua_ke",
                "label": "Cụm: Quyền Thừa kế & Phân chia Di sản",
                "type": "Cluster",
                "color": "#8b5cf6",
                "value": 24,
                "title": "Quy định Di chúc, Hiệu lực di chúc và Thừa kế theo pháp luật",
            },
            {
                "id": "law_d624",
                "label": "Điều 624: Định nghĩa Di chúc",
                "type": "Law",
                "color": "#10b981",
                "value": 17,
                "title": "Di chúc là sự thể hiện ý chí của cá nhân nhằm định đoạt tài sản sau khi chết.",
            },
            {
                "id": "law_d629",
                "label": "Điều 629: Điều kiện Di chúc miệng",
                "type": "Law",
                "color": "#10b981",
                "value": 21,
                "title": "Di chúc miệng chỉ hợp pháp khi người lập di chúc thể hiện ý chí trước ít nhất 2 người làm chứng.",
            },
            {
                "id": "law_d630",
                "label": "Điều 630: Di chúc hợp pháp",
                "type": "Law",
                "color": "#10b981",
                "value": 19,
                "title": "Người lập di chúc minh mẫn, sáng suốt; nội dung không trái pháp luật, đạo đức xã hội.",
            },
            {
                "id": "law_d651",
                "label": "Điều 651: Thừa kế theo pháp luật",
                "type": "Law",
                "color": "#10b981",
                "value": 22,
                "title": "Khi di chúc không hợp pháp, di sản chia đều cho những người cùng hàng thừa kế.",
            },
            {
                "id": "case_thua_ke_03",
                "label": "Bản án 105/2022/DS-ST",
                "type": "Case",
                "color": "#3b82f6",
                "value": 16,
                "title": "Vô hiệu di chúc miệng không có người làm chứng độc lập, chia đều nhà đất cho 3 người con.",
            },
        ],
        "edges": [
            {
                "from": "query_inherit",
                "to": "law_d629",
                "label": "KIỂM TRA HIỆU LỰC (VÔ HIỆU)",
                "color": "#ef4444",
            },
            {
                "from": "query_inherit",
                "to": "law_d651",
                "label": "CHIA ĐỀU THEO HÀNG 1",
                "color": "#ef4444",
            },
            {
                "from": "law_d624",
                "to": "cluster_thua_ke",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d629",
                "to": "cluster_thua_ke",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d651",
                "to": "cluster_thua_ke",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "case_thua_ke_03",
                "to": "law_d629",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
            {
                "from": "case_thua_ke_03",
                "to": "law_d651",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
        ],
    },
    "tort": {
        "query": "Bồi thường Thiệt hại Ngoài Hợp đồng do Cây cối gãy đổ đè ô tô",
        "nodes": [
            {
                "id": "query_tort",
                "label": "Vụ việc đang xét: Cây đổ đè hỏng ô tô",
                "type": "Query",
                "color": "#ef4444",
                "value": 26,
                "title": "Cây cổ thụ bật gốc đè ô tô trong bão, yêu cầu bồi thường 180 triệu đồng.",
            },
            {
                "id": "cluster_boi_thuong",
                "label": "Cụm: Bồi thường Thiệt hại Ngoài HĐ",
                "type": "Cluster",
                "color": "#8b5cf6",
                "value": 24,
                "title": "Trách nhiệm bồi thường do tài sản, súc vật, cây cối",
            },
            {
                "id": "law_d584",
                "label": "Điều 584: Căn cứ phát sinh trách nhiệm",
                "type": "Law",
                "color": "#10b981",
                "value": 19,
                "title": "Xâm phạm tài sản gây thiệt hại phải bồi thường; trừ trường hợp bất khả kháng hoàn toàn.",
            },
            {
                "id": "law_d585",
                "label": "Điều 585: Nguyên tắc bồi thường thiệt hại",
                "type": "Law",
                "color": "#10b981",
                "value": 18,
                "title": "Thiệt hại thực tế phải được bồi thường toàn bộ và kịp thời.",
            },
            {
                "id": "law_d604",
                "label": "Điều 604: Cây cối gây thiệt hại",
                "type": "Law",
                "color": "#10b981",
                "value": 22,
                "title": "Chủ sở hữu, người quản lý cây cối phải bồi thường thiệt hại do cây cối gây ra.",
            },
            {
                "id": "case_cay_do_04",
                "label": "Bản án 29/2024/DS-ST",
                "type": "Case",
                "color": "#3b82f6",
                "value": 16,
                "title": "Buộc chủ quản lý cây bồi thường vì không tiến hành kiểm tra tỉa cành định kỳ trước mùa bão.",
            },
        ],
        "edges": [
            {
                "from": "query_tort",
                "to": "law_d604",
                "label": "ÁP DỤNG ĐIỀU 604",
                "color": "#ef4444",
            },
            {
                "from": "query_tort",
                "to": "law_d584",
                "label": "XÁC ĐỊNH LỖI QUẢN LÝ",
                "color": "#ef4444",
            },
            {
                "from": "law_d584",
                "to": "cluster_boi_thuong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "law_d604",
                "to": "cluster_boi_thuong",
                "label": "BELONGS_TO_CLUSTER",
                "color": "#8b5cf6",
            },
            {
                "from": "case_cay_do_04",
                "to": "law_d604",
                "label": "RELATES_TO_LAW",
                "color": "#10b981",
            },
        ],
    },
}
